import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHtml5,
  faReact,
  faSwift,
  faNodeJs,
  faCss3,
  faJsSquare,
  faNode,
} from "@fortawesome/free-brands-svg-icons";
import { useState } from "react";
import sgMail from "@sendgrid/mail";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [name, setName] = useState("");

  function validateForm() {
    let isValid = true;

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      isValid = false;
      console.log("Please enter a valid email address");
    }

    // Validate message length
    if (message.length < 1) {
      isValid = false;
      console.log("Please enter a message");
    }

    // Validate name length
    if (name.length < 1) {
      isValid = false;
      console.log("Please enter a name");
    }

    return isValid;
  }

  const handleSend = async () => {
    const msg = {
      to: "johnmccants002@gmail.com", // Change to your recipient
      from: "johnmccants2@hotmail.com", // Change to your verified sender
      subject: "Victory Labs Contact",
      text: `${message} from: ${email}`,
      html: "<strong>and easy to do anywhere, even with Node.js</strong>",
    };
    console.log("In handle send this is the msg object", msg);
    if (validateForm()) {
      const response = await fetch("/api/send-email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(msg),
      });
      const data = await response.json();
      setEmail("");
      setMessage("");
      setName("");
      alert("Message Sent!");
      console.log(data.message);
    } else {
      alert("Please fill out all fields correctly.");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav class="bg-white">
          <div class="container mx-auto px-6 py-4">
            <div class="flex justify-between items-center">
              <div class="w-full md:w-auto text-gray-800 font-bold text-xl">
                <Link class="text-gray-800 hover:text-gray-700" href="#">
                  Victory Labs
                </Link>
              </div>
              <div class="flex items-center -mx-2">
                <Link class="mx-2 text-gray-600 hover:text-gray-800" href="/">
                  Home
                </Link>
                <Link
                  href="/services"
                  class="mx-2 text-gray-600 hover:text-gray-800"
                >
                  Services
                </Link>

                <Link class="mx-2 text-gray-600 hover:text-gray-800" href="#">
                  Portfolio
                </Link>
                <Link
                  class="mx-2 text-gray-600 hover:text-gray-800"
                  href="https://blog.victorylabs.io"
                >
                  Blog
                </Link>
                <Link
                  class="mx-2 text-gray-600 hover:text-gray-800"
                  href="#contactUs"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </nav>
        <section className={`${styles.sectionClass} ${styles.valuepropheader}`}>
          <div
            class={`${styles.mainContainer} ${styles.valuepropheaderContainer}`}
          >
            <h1 className={`${styles.valuepropheaderH1}`}>Victory Labs</h1>
            <h2
              className={`${styles.sectionClassH2} ${styles.valuepropheaderH2}`}
            >
              Your Partner in Software Development
            </h2>
            <Link
              href="#plans"
              class={`${styles.btn} ${styles.valuepropheaderBtn}`}
            >
              Get Started
            </Link>
          </div>
        </section>
        <section class="bg-gray-100 sectionClass">
          <div class="container mx-auto px-6 py-20">
            <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">
              About Victory Labs
            </h2>
            <div class="flex flex-wrap">
              <div class="w-full md:w-1/2 p-6">
                <h3 class="text-2xl font-bold text-gray-800 mb-3">
                  Who we are
                </h3>
                <p
                  class={`text-gray-600 leading-loose ${styles.sectionClassP}`}
                >
                  Victory Labs is a software development company that creates
                  custom software solutions for businesses of all sizes. We
                  specialize in solving complex problems with technology, and
                  helping our clients achieve their goals.
                </p>
              </div>
              <div class="w-full md:w-1/2 p-6">
                <h3 class="text-2xl font-bold text-gray-800 mb-3">
                  What we do
                </h3>
                <p class="text-gray-600 leading-loose">
                  Our team of experienced developers, designers, and project
                  managers work together to build software that drives growth,
                  solves problems, and improves efficiency. We take a
                  collaborative approach with our clients to ensure that their
                  needs are met at every step of the development process.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section id="technologies" class="bg-white-100 py-20 sectionClass">
          <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12">
              Technologies Used
            </h2>
            <ul class="flex flex-wrap justify-center items-center tech-list">
              <li class="mx-10 my-6 flex flex-col items-center">
                <FontAwesomeIcon icon={faHtml5} size={"4x"} color={"#b89c6e"} />
                <span class="text-center">HTML5</span>
              </li>
              <li class="mx-10 my-6 flex flex-col items-center">
                <FontAwesomeIcon icon={faCss3} size={"4x"} color={"#b89c6e"} />
                <span class="text-center">CSS3</span>
              </li>
              <li class="mx-10 my-6 flex flex-col items-center">
                <FontAwesomeIcon
                  icon={faJsSquare}
                  size={"4x"}
                  color={"#b89c6e"}
                />
                <span class="text-center">JavaScript</span>
              </li>
              <li class="mx-10 my-6 flex flex-col items-center">
                <FontAwesomeIcon icon={faReact} size={"4x"} color={"#b89c6e"} />
                <span class="text-center">React</span>
              </li>
              <li class="mx-10 my-6 flex flex-col items-center">
                <FontAwesomeIcon icon={faSwift} size={"4x"} color={"#b89c6e"} />
                <span class="text-center">Swift</span>
              </li>
              <li class="mx-10 my-6 flex flex-col items-center">
                <FontAwesomeIcon icon={faNode} size={"4x"} color={"#b89c6e"} />
                <span class="text-center">Node</span>
              </li>
            </ul>
          </div>
        </section>

        <section class="bg-gray-100 sectionClass">
          <div class="container mx-auto px-6 py-20">
            <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">
              Our Work
            </h2>
            <div class="flex flex-wrap">
              <div class="w-full md:w-1/3 p-6">
                <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                  <Link href="#">
                    <img
                      class="lg:h-48 md:h-36 w-full object-cover object-center"
                      src="/images/japanesemobile.png"
                      alt="Site 1"
                    />
                  </Link>
                  <div class="p-6">
                    <h3 class="title-font text-lg font-medium text-gray-900 mb-3">
                      Japanese Mobile App
                    </h3>
                    <p class="leading-relaxed mb-3 text-gray-900">
                      Japans leading mobile app for train schedules and route
                      planning, HyperDia is the go-to solution for locals and
                      tourists alike. With real-time updates, fare information,
                      and even wheelchair accessibility details, HyperDia
                      provides comprehensive and reliable transportation
                      information for navigating Japans complex train system.
                    </p>
                    <Link
                      class="text-indigo-500 inline-flex items-center"
                      href="#"
                    >
                      Learn More
                    </Link>
                  </div>
                </div>
              </div>
              <div class="w-full md:w-1/3 p-6">
                <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                  <Link href="#">
                    <img
                      class="lg:h-48 md:h-36 w-full object-cover object-center"
                      src="/images/folk.png"
                      alt="Site 2"
                    />
                  </Link>
                  <div class="p-6">
                    <h3 class="title-font text-lg font-medium text-gray-900 mb-3">
                      Artesanías Mexicanas: Exploring the Rich Traditions of
                      Mexican Folk Art
                    </h3>
                    <p class="leading-relaxed mb-3 text-gray-900">
                      Immerse yourself in the rich culture and vibrant colors of
                      Mexican folk art with our website. Our collection features
                      a wide range of traditional crafts, from intricately
                      designed pottery and textiles to colorful paper mache
                      sculptures and vibrant hand-carved wooden masks. Discover
                      the history and meaning behind each piece and explore the
                      diverse styles and techniques used by artisans throughout
                      Mexico.
                    </p>
                    <Link
                      class="text-indigo-500 inline-flex items-center"
                      href="#"
                    >
                      Learn more
                    </Link>
                  </div>
                </div>
              </div>
              <div class="w-full md:w-1/3 p-6">
                <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                  <Link href="#">
                    <img
                      class="lg:h-48 md:h-36 w-full object-cover object-center"
                      src="/images/mgs.png"
                      alt="Site 3"
                    />
                  </Link>
                  <div class="p-6">
                    <h3 class="title-font text-lg font-medium text-gray-900 mb-3">
                      Metal Gear Fandom
                    </h3>
                    <p class={`leading-relaxed mb-3 text-gray-900`}>
                      Join the community of Metal Gear Solid fans and immerse
                      yourself in the thrilling world of espionage, action, and
                      stealth. Our fan page is dedicated to all things Metal
                      Gear Solid, from in-depth analysis of the games' intricate
                      plotlines and characters, to discussions about the latest
                      news and rumors surrounding the beloved franchise. Connect
                      with like-minded fans and share your love for one of the
                      most iconic and influential video game series of all time.
                    </p>
                    <Link
                      class="text-indigo-500 inline-flex items-center"
                      href="#"
                    >
                      Learn More
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="bg-white sectionClass">
          <div class="container mx-auto px-6 py-20">
            <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">
              Choose Your Plan
            </h2>
            <div class="flex flex-wrap">
              <div class="w-full md:w-1/3 px-6 mb-4">
                <div class="h-full bg-gray-100 p-8 rounded-lg overflow-hidden text-center relative">
                  <h3 class="text-gray-900 font-bold text-xl mb-3">Basic</h3>
                  <div class="text-gray-600 font-bold text-5xl mb-2">
                    $19<span class="text-gray-500 text-base">/mo</span>
                  </div>
                  <p class="text-gray-500 mb-5">Up to 5 projects</p>
                  <Link
                    class="bg-gray-800 text-white py-2 px-4 rounded-full text-sm hover:bg-gray-600 hover:text-white focus:outline-none focus:shadow-outline"
                    href="#"
                  >
                    Select Plan
                  </Link>
                  <div class="absolute bottom-0 right-0 bg-red-500 px-3 py-2 mr-4 text-xs font-bold rounded-full text-white">
                    Most Popular
                  </div>
                </div>
              </div>
              <div class="w-full md:w-1/3 px-6 mb-4">
                <div class="h-full bg-gray-100 p-8 rounded-lg overflow-hidden text-center relative">
                  <h3 class="text-gray-900 font-bold text-xl mb-3">Pro</h3>
                  <div class="text-gray-600 font-bold text-5xl mb-2">
                    $39<span class="text-gray-500 text-base">/mo</span>
                  </div>
                  <p class="text-gray-500 mb-5">Up to 20 projects</p>
                  <Link
                    class="bg-gray-800 text-white py-2 px-4 rounded-full text-sm hover:bg-gray-600 hover:text-white focus:outline-none focus:shadow-outline"
                    href="#"
                  >
                    Select plan
                  </Link>
                </div>
              </div>
              <div class="w-full md:w-1/3 px-6 mb-4">
                <div class="h-full bg-gray-100 p-8 rounded-lg overflow-hidden text-center relative">
                  <h3 class="text-gray-900 font-bold text-xl mb-3">
                    Enterprise
                  </h3>
                  <div class="text-gray-600 font-bold text-5xl mb-2">
                    $99<span class="text-gray-500 text-base">/mo</span>
                  </div>
                  <p class="text-gray-500 mb-5">Unlimited projects</p>
                  <Link
                    class="bg-gray-800 text-white py-2 px-4 rounded-full text-sm hover:bg-gray-600 hover:text-white focus:outline-none focus:shadow-outline"
                    href="#"
                  >
                    Select plan
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="bg-gray-100 sectionClass" id="contactUs">
          <div class={`mx-auto px-6 py-20`}>
            <h2
              class={`${styles.sectionClassH2} text-4xl font-bold text-center text-gray-800 mb-8`}
            >
              Contact Us
            </h2>
            <div class="w-full max-w-2xl mx-auto">
              <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                <div class="mb-4">
                  <label class="block text-gray-700 font-bold mb-2" for="name">
                    Name
                  </label>
                  <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="name"
                    type="text"
                    placeholder="John Doe"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                  />
                </div>
                <div class="mb-4">
                  <label class="block text-gray-700 font-bold mb-2" for="email">
                    Email
                  </label>
                  <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="email"
                    type="email"
                    placeholder="johndoe@example.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </div>
                <div class="mb-4">
                  <label
                    class="block text-gray-700 font-bold mb-2"
                    for="message"
                  >
                    Message
                  </label>
                  <textarea
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="message"
                    placeholder="Write your message here..."
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                  ></textarea>
                </div>
                <div class="mb-4">
                  <button
                    class="bg-gray-800 text-white py-2 px-4 rounded-full text-sm hover:bg-gray-600 hover:text-white focus:outline-none focus:shadow-outline"
                    type="button"
                    onClick={handleSend}
                  >
                    Send Message
                  </button>
                </div>
              </form>
            </div>
          </div>
        </section>
        <footer class="bg-gray-800 pt-10 sm:mt-10 pt-10">
          <div class="container mx-auto px-6">
            <div class="flex flex-wrap justify-center">
              <div class="w-full sm:w-1/2 px-6">
                <div class="text-white">
                  <h3 class="font-bold text-xl mb-2">Victory Labs</h3>
                  <p class="mb-2">
                    Victory Labs is a software development company that
                    specializes in creating custom solutions for businesses.
                  </p>
                  <p>
                    <Link href="#" class="hover:underline">
                      Learn More
                    </Link>
                  </p>
                </div>
              </div>
              <div class="w-full sm:w-1/4 px-6">
                <h3 class="font-bold text-xl text-white mb-2">Links</h3>
                <ul class="list-reset mb-2">
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <Link href="faq.html" class="text-white hover:underline">
                      FAQ
                    </Link>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <Link href="#" class="text-white hover:underline">
                      Help
                    </Link>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <Link href="#" class="text-white hover:underline">
                      Support
                    </Link>
                  </li>
                </ul>
              </div>
              <div class="w-full sm:w-1/4 px-6">
                <h3 class="font-bold text-xl text-white mb-2">Social Media</h3>
                <ul class="list-reset mb-2">
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <Link href="#" class="text-white hover:underline">
                      Twitter
                    </Link>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <Link href="#" class="text-white hover:underline">
                      Facebook
                    </Link>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <Link href="#" class="text-white hover:underline">
                      Instagram
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <hr class="h-px my-6 bg-gray-700 border-none" />
            <div class="flex flex-col md:flex-row md:items-center md:justify-between">
              <div>
                <p class="text-center md:text-left text-white">
                  © 2023 Victory Labs. All rights reserved.
                </p>
              </div>
              <div class="flex items-center">
                <Link href="#" class="text-white hover:underline mx-4">
                  Privacy Policy
                </Link>
                <Link href="#" class="text-white hover:underline">
                  Terms of Service
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
