import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <nav class="bg-white">
          <div class="container mx-auto px-6 py-4">
            <div class="flex justify-between items-center">
              <div class="w-full md:w-auto text-gray-800 font-bold text-xl">
                <a class="text-gray-800 hover:text-gray-700" href="#">
                  Victory Labs
                </a>
              </div>
              <div class="flex items-center -mx-2">
                <a class="mx-2 text-gray-600 hover:text-gray-800" href="/">
                  Home
                </a>

                <a
                  href="/services"
                  class="mx-2 text-gray-600 hover:text-gray-800"
                >
                  Services
                </a>

                <a class="mx-2 text-gray-600 hover:text-gray-800" href="#">
                  Portfolio
                </a>
                <a
                  class="mx-2 text-gray-600 hover:text-gray-800"
                  href="blogs.html"
                >
                  Blog
                </a>
                <a class="mx-2 text-gray-600 hover:text-gray-800" href="#">
                  Contact
                </a>
              </div>
            </div>
          </div>
        </nav>
        <section class="py-20 bg-gray-100">
          <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12">
              Website Development Services
            </h2>
            <div class="flex flex-wrap -mx-4">
              <div class="w-full md:w-1/2 px-4 mb-8">
                {/* <img
                    src="/images/webdev.png"
                    alt="Website Development"
                    class="w-full h-auto"
                  /> */}
              </div>
              <div class="w-full md:w-1/2 px-4">
                <h3 class="text-2xl font-bold mb-4">
                  HTML, CSS, and JavaScript
                </h3>
                <p class="text-gray-700 mb-4">
                  Our team of web developers are experts in building websites
                  using the latest HTML, CSS, and JavaScript technologies. We
                  work closely with our clients to design and develop custom
                  websites that meet their unique needs.
                </p>
                <h3 class="text-2xl font-bold mb-4">React and Node</h3>
                <p class="text-gray-700 mb-4">
                  We specialize in building web applications using popular
                  frameworks like React and Node. Our team has extensive
                  experience in building scalable and performant web
                  applications using these technologies.
                </p>
                <h3 class="text-2xl font-bold mb-4">
                  Content Management Systems
                </h3>
                <p class="text-gray-700 mb-4">
                  We work with a variety of content management systems like
                  WordPress and Squarespace to help our clients easily manage
                  their website content. We can also build custom content
                  management systems for clients with unique needs.
                </p>
                <a
                  href="#"
                  class="inline-block px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                >
                  Learn More
                </a>
              </div>
            </div>
          </div>
        </section>
        <section class="py-20 bg-gray-100">
          <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12">
              Mobile App Development Services
            </h2>
            <div class="flex flex-wrap -mx-4">
              <div class="w-full md:w-1/2 px-4 mb-8">
                {/* <img
                    src="/images/mobiledev.png"
                    alt="Mobile App Development"
                    class="w-full h-auto"
                  /> */}
              </div>
              <div class="w-full md:w-1/2 px-4">
                <h3 class="text-2xl font-bold mb-4">React Native</h3>
                <p class="text-gray-700 mb-4">
                  Our team of mobile app developers are experts in building
                  mobile applications using the popular React Native framework.
                  We can help bring your mobile app ideas to life using this
                  powerful technology.
                </p>
                <h3 class="text-2xl font-bold mb-4">
                  Cross-Platform Development
                </h3>
                <p class="text-gray-700 mb-4">
                  We specialize in building cross-platform mobile applications
                  that work seamlessly on both iOS and Android devices. This
                  approach allows us to deliver high-quality mobile applications
                  that are cost-effective and scalable.
                </p>
                <h3 class="text-2xl font-bold mb-4">Custom Development</h3>
                <p class="text-gray-700 mb-4">
                  We can build custom mobile applications that are tailored to
                  your specific business needs. Our team can work with you to
                  design and develop mobile applications that meet your unique
                  requirements.
                </p>
                <a
                  href="#"
                  class="inline-block px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                >
                  Learn More
                </a>
              </div>
            </div>
          </div>
        </section>
        <section class="py-20 bg-gray-100">
          <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12">
              Logo and Marketing Design Services
            </h2>
            <div class="flex flex-wrap -mx-4">
              <div class="w-full md:w-1/2 px-4 mb-8">
                {/* <img
                    src="/images/marketing.png"
                    alt="Logo and Marketing Design"
                    class="w-full h-auto"
                  /> */}
              </div>
              <div class="w-full md:w-1/2 px-4">
                <h3 class="text-2xl font-bold mb-4">Midjourney</h3>
                <p class="text-gray-700 mb-4">
                  Our team of designers use Midjourney, a powerful design
                  software, to create stunning logos and marketing materials. We
                  work closely with our clients to design logos that accurately
                  represent their brand and marketing materials that resonate
                  with their target audience.
                </p>
                <h3 class="text-2xl font-bold mb-4">DALL-E</h3>
                <p class="text-gray-700 mb-4">
                  We use the latest AI technology, DALL-E, to create unique and
                  eye-catching designs that set our clients apart from their
                  competition. Our team can help you create a brand identity
                  that stands out and connects with your customers.
                </p>
                <h3 class="text-2xl font-bold mb-4">Consulting Services</h3>
                <p class="text-gray-700 mb-4">
                  In addition to design services, we also offer consulting
                  services to help our clients develop effective marketing
                  strategies. Our team can work with you to identify your target
                  audience, develop messaging that resonates with them, and
                  create a plan for promoting your brand.
                </p>
                <a
                  href="#"
                  class="inline-block px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                >
                  Learn More
                </a>
              </div>
            </div>
          </div>
        </section>
        <section class="py-20">
          <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12">
              Website Development Work
            </h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <div class="bg-white rounded-lg overflow-hidden shadow-lg">
                {/* <img
                    src="https://via.placeholder.com/800x500.png?text=Website+Development+Project"
                    alt="Website Development Project"
                    class="w-full h-auto"
                  /> */}
                <div class="px-6 py-4">
                  <h3 class="text-2xl font-bold mb-2">Project Title</h3>
                  <p class="text-gray-700 text-base">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    pellentesque erat non libero ullamcorper, vel auctor sapien
                    lacinia.
                  </p>
                  <a
                    href="#"
                    class="inline-block mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                  >
                    Learn More
                  </a>
                </div>
              </div>
              <div class="bg-white rounded-lg overflow-hidden shadow-lg">
                {/* <img
                    src="https://via.placeholder.com/800x500.png?text=Website+Development+Project"
                    alt="Website Development Project"
                    class="w-full h-auto"
                  /> */}
                <div class="px-6 py-4">
                  <h3 class="text-2xl font-bold mb-2">Project Title</h3>
                  <p class="text-gray-700 text-base">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    pellentesque erat non libero ullamcorper, vel auctor sapien
                    lacinia.
                  </p>
                  <a
                    href="#"
                    class="inline-block mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                  >
                    Learn More
                  </a>
                </div>
              </div>
              <div class="bg-white rounded-lg overflow-hidden shadow-lg">
                {/* <img
                    src="https://via.placeholder.com/800x500.png?text=Website+Development+Project"
                    alt="Website Development Project"
                    class="w-full h-auto"
                  /> */}
                <div class="px-6 py-4">
                  <h3 class="text-2xl font-bold mb-2">Project Title</h3>
                  <p class="text-gray-700 text-base">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    pellentesque erat non libero ullamcorper, vel auctor sapien
                    lacinia.
                  </p>
                  <a
                    href="#"
                    class="inline-block mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                  >
                    Learn More
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>

        <footer class="bg-gray-800 pt-10 sm:mt-10 pt-10">
          <div class="container mx-auto px-6">
            <div class="flex flex-wrap justify-center">
              <div class="w-full sm:w-1/2 px-6">
                <div class="text-white">
                  <h3 class="font-bold text-xl mb-2">Victory Labs</h3>
                  <p class="mb-2">
                    Victory Labs is a software development company that
                    specializes in creating custom solutions for businesses.
                  </p>
                  <p>
                    <a href="#" class="hover:underline">
                      Learn More
                    </a>
                  </p>
                </div>
              </div>
              <div class="w-full sm:w-1/4 px-6">
                <h3 class="font-bold text-xl text-white mb-2">Links</h3>
                <ul class="list-reset mb-2">
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a href="#" class="text-white hover:underline">
                      FAQ
                    </a>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a href="#" class="text-white hover:underline">
                      Help
                    </a>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a href="#" class="text-white hover:underline">
                      Support
                    </a>
                  </li>
                </ul>
              </div>
              <div class="w-full sm:w-1/4 px-6">
                <h3 class="font-bold text-xl text-white mb-2">Social Media</h3>
                <ul class="list-reset mb-2">
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a href="#" class="text-white hover:underline">
                      Twitter
                    </a>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a href="#" class="text-white hover:underline">
                      Facebook
                    </a>
                  </li>
                  <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a href="#" class="text-white hover:underline">
                      Instagram
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <hr class="h-px my-6 bg-gray-700 border-none" />
            <div class="flex flex-col md:flex-row md:items-center md:justify-between">
              <div>
                <p class="text-center md:text-left text-white">
                  © 2023 Victory Labs. All rights reserved.
                </p>
              </div>
              <div class="flex items-center">
                <a href="#" class="text-white hover:underline mx-4">
                  Privacy Policy
                </a>
                <a href="#" class="text-white hover:underline">
                  Terms of Service
                </a>
              </div>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
