import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Services() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section class="py-20 bg-gray-100">
          <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12">
              Website Development Services
            </h2>
            <div class="flex flex-wrap -mx-4">
              <div class="w-full md:w-1/2 px-4 mb-8">
                <img
                  src="/images/webdev.png"
                  alt="Website Development"
                  class="w-full h-auto"
                />
              </div>
              <div class="w-full md:w-1/2 px-12">
                <h3 class="text-2xl font-bold mb-4">Simple Website Services</h3>
                <p class="text-gray-700 mb-4">
                  Our team is really good at creating websites. Think of us like
                  digital architects and builders who make sure your website
                  looks great and works smoothly. We chat with you to understand
                  what you need, and then we put together a website that fits
                  just right for your business or personal use.
                </p>
                <h3 class="text-2xl font-bold mb-4">
                  Advanced Website Services
                </h3>
                <p class="text-gray-700 mb-4">
                  We're also experts in making websites that can do a bit more
                  complex stuff, like online stores or platforms that need to
                  handle lots of visitors at once. We use some of the best tools
                  out there to build these, ensuring your website is fast and
                  reliable.
                </p>
                <h3 class="text-2xl font-bold mb-4">
                  Content Management For Your Business
                </h3>
                <p class="text-gray-700 mb-4">
                  Plus, if you've ever heard about the hassle of updating
                  website content and thought, "That sounds like a nightmare,"
                  we've got you covered. We set up easy-to-use systems that let
                  you change or add anything on your website without needing to
                  call in a pro. And if you need something really special, we
                  can make a custom system that fits exactly what you're looking
                  for.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section class="py-20 bg-gray-100">
          <div class="container mx-auto px-12">
            <h2 class="text-4xl font-bold text-center mb-12">
              Mobile App Development Services
            </h2>
            <div class="flex flex-wrap -mx-4">
              <div class="w-full md:w-1/2 px-4 mb-8">
                <img
                  src="/images/mobiledev.png"
                  alt="Mobile App Development"
                  class="w-full h-auto"
                />
              </div>
              <div class="w-full md:w-1/2 px-4">
                <h3 class="text-2xl font-bold mb-4">React Native</h3>
                <p class="text-gray-700 mb-4">
                  Our team of mobile app developers are experts in building
                  mobile applications using the popular React Native framework.
                  We can help bring your mobile app ideas to life using this
                  powerful technology.
                </p>
                <h3 class="text-2xl font-bold mb-4">
                  Cross-Platform Development
                </h3>
                <p class="text-gray-700 mb-4">
                  We specialize in building cross-platform mobile applications
                  that work seamlessly on both iOS and Android devices. This
                  approach allows us to deliver high-quality mobile applications
                  that are cost-effective and scalable.
                </p>
                <h3 class="text-2xl font-bold mb-4">Custom Development</h3>
                <p class="text-gray-700 mb-4">
                  We can build custom mobile applications that are tailored to
                  your specific business needs. Our team can work with you to
                  design and develop mobile applications that meet your unique
                  requirements.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section class="py-20 bg-gray-100">
          <div class="container mx-auto px-12">
            <h2 class="text-4xl font-bold text-center mb-12">
              Logo and Marketing Design Services
            </h2>
            <div class="flex flex-wrap -mx-4">
              <div class="w-full md:w-1/2 px-4 mb-8">
                <img
                  src="/images/marketing.png"
                  alt="Logo and Marketing Design"
                  class="w-full h-auto"
                />
              </div>
              <div class="w-full md:w-1/2 px-4">
                <h3 class="text-2xl font-bold mb-4">Midjourney</h3>
                <p class="text-gray-700 mb-4">
                  Our team of designers use Midjourney, a powerful design
                  software, to create stunning logos and marketing materials. We
                  work closely with our clients to design logos that accurately
                  represent their brand and marketing materials that resonate
                  with their target audience.
                </p>
                <h3 class="text-2xl font-bold mb-4">DALL-E</h3>
                <p class="text-gray-700 mb-4">
                  We use the latest AI technology, DALL-E, to create unique and
                  eye-catching designs that set our clients apart from their
                  competition. Our team can help you create a brand identity
                  that stands out and connects with your customers.
                </p>
                <h3 class="text-2xl font-bold mb-4">Consulting Services</h3>
                <p class="text-gray-700 mb-4">
                  In addition to design services, we also offer consulting
                  services to help our clients develop effective marketing
                  strategies. Our team can work with you to identify your target
                  audience, develop messaging that resonates with them, and
                  create a plan for promoting your brand.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section class="py-20 px-8">
          <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12">
              Website Development Work
            </h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <div class="bg-white rounded-lg overflow-hidden shadow-lg">
                <img
                  src="/images/fetchit.png"
                  alt="Website Development Project"
                  class="w-full h-auto"
                />
                <div class="px-6 py-4">
                  <h3 class="text-2xl font-bold mb-2">FetchIt AI Platform</h3>
                  <p class="text-gray-700 text-base">
                    AI Learning Platform that utilizes ChatGPT to enhance
                    students learning.
                  </p>
                  <Link
                    href="https://www.fetchit.cc/"
                    class="inline-block mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                  >
                    View Page
                  </Link>
                </div>
              </div>
              <div class="bg-white rounded-lg overflow-hidden shadow-lg">
                <img
                  src="/images/elevatelawn.png"
                  alt="Website Development Project"
                  class="w-full h-auto"
                />
                <div class="px-6 py-4">
                  <h3 class="text-2xl font-bold mb-2">Elevate Lawn Care</h3>
                  <p class="text-gray-700 text-base">
                    Elevate Lawn Care provides routine lawn care services,
                    property clean-ups, and garden design for residential Rancho
                    Cordova, Folsom, and El Dorado Hills, California properties.
                    Schedule an estimate with us today and let us work with you
                    on maintaining a beautiful yard year-round
                  </p>
                  <Link
                    href="https://www.elevatelawn.care/"
                    class="inline-block mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                  >
                    View Page
                  </Link>
                </div>
              </div>
              <div class="bg-white rounded-lg overflow-hidden shadow-lg">
                <img
                  src="/images/aftershock.png"
                  alt="Website Development Project"
                  class="w-full h-auto"
                />
                <div class="px-6 py-4">
                  <h3 class="text-2xl font-bold mb-2">AfterShock Festival</h3>
                  <p class="text-gray-700 text-base">
                    This is a landing page used to navigate info and content
                    about the upcoming Aftershock music festival which is being
                    held in Sacramento, CA this year (2024) from 10/10 - 10/13
                  </p>
                  <Link
                    href="https://jake10693.github.io/AfterShock_Event_Flyer_Landing_Page/"
                    class="inline-block mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                  >
                    View Page
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
